##' saveManifest
##'
##' Save a package or session manifest to file.
##'
##' @param manifest The object to save as a serialized package or session
##' manfiest. A session manifest will be generated by libManifest as necessary.
##' @param fname Name (including path) of the file to save
##' @param ... Unused
##'
##' @return The name of the file written 
##'
##' @export
setGeneric("saveManifest", function(manifest, fname = "./pkg_manifest.rman",...) standardGeneric("saveManifest"))

setMethod("saveManifest", "PkgManifest",
          function(manifest, fname, ...) {
              con = file(fname, "w")
              cat("# R manifest\n", file = con)
              cat("# Manifest type: package\n", file = con, append = TRUE)
              cat(sprintf("# Dependency repositories: %d\n",
                          length(dep_repos(manifest))),
                  file = con, append = TRUE)
              sapply(dep_repos(manifest), function(x) {
                  cat(sprintf("# repo: %s\n", x), file = con,
                      append = TRUE)
              })
              write.table(manifest_df(manifest), file = con, append=TRUE,
                          sep = ",")

              close(con)
              fname
          })


setMethod("saveManifest", "SessionManifest",
          function(manifest, fname, ...) {
              con = file(fname, "w")
              cat("# R manifest\n", file = con)
              cat("# Manifest type: session\n", file = con, append = TRUE)
              cat(sprintf("# Dependency repositories: %d\n",
                          length(dep_repos(manifest))),
                  file = con, append = TRUE)
              sapply(dep_repos(manifest), function(x) {
                  cat(sprintf("# repo: %s\n", x), file = con,
                      append = TRUE)
              })

              df = manifest_df(manifest)
              df = merge(df, versions_df(manifest), by = "name")
              write.table(df, file = con, append=TRUE,
                          sep = ",")

              close(con)
              fname
          })


setMethod("saveManifest", "missing",
          function(manifest, fname, ...) {
              saveManifest(currentCompEnv(), fname = fname, ...)
          })

setMethod("saveManifest", "SwitchrCtx",
          function(manifest, fname, ...) {
              saveManifest(libManifest(manifest, ...), fname = fname, ...)
          })
